### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Denperidge** [Denperidge/denperidge.github.io#5]
- [x] Dynamic OpenGraph
- [ ] Images for projects
- [ ] Index page css-based reveal (use labels, aria-hidden, aria-disabled, aria-,,,clickable?)
- [ ] Update characters text

**Comment by Denperidge** [comment]
Dynamic opengraph added in c95dc7f9fa3eed5c1d9fc808e9da6710b9426a86

**Comment by Denperidge** [comment]
Additionally:

- [ ] Add link to repo
- [ ] Add NIS & lblod
